myapp/urls.py
from django.urls import path, include
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from . import views


app_name = 'myapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/select/', views.select, name='select'),
    path('<int:pk>/deselect/', views.deselect, name='deselect'),
    path('admin-panel/', views.AdminPanelView.as_view(), name='admin_panel'),
    path('create-user/', views.create_user, name='create_user'),
    path('<int:pk>/delete-user/', views.delete_user, name='delete_user'),
    path('view-users/', views.UsersView.as_view(), name='view_users'),
    path('create-destination/', views.create_destination, name='create_destination'),
    path('<int:pk>/delete-destination/', views.delete_destination, name='delete_destination'),
    path('view-destinations/', views.DestinationsView.as_view(), name='view_destinations'),
    path('<int:pk>/payment/', views.make_payment, name="make_payment"),
    path('<int:pk>/payment-success/', views.payment_success, name="payment_success"),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('change-password/', views.change_password, name='change_password'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='myapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='myapp/logout.html'), name='logout'),
    path('password-reset/',
      auth_views.PasswordResetView.as_view(template_name='myapp/password_reset.html',
      success_url=reverse_lazy('myapp:password_reset_done'), email_template_name = 'myapp/password_reset_email.html'),
      name='password_reset'),
    path('password-reset/done/',
      auth_views.PasswordResetDoneView.as_view(template_name='myapp/password_reset_done.html'),
      name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
      auth_views.PasswordResetConfirmView.as_view(template_name='myapp/password_reset_confirm.html', success_url=reverse_lazy(
        'myapp:password_reset_complete')),
      name='password_reset_confirm'),
    path('password-reset-complete/',
      auth_views.PasswordResetCompleteView.as_view(template_name='myapp/password_reset_complete.html'),
      name='password_reset_complete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
import datetime

# Create your models here.

class User(AbstractUser):
    CLIENTUSER = 1
    MODERATOR = 2
    ROLE_CHOICES = (
        (CLIENTUSER, 'Clientuser'),
        (MODERATOR, 'Moderator'),
    )
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)

    def __str__(self):
        return '{0} User'.format(self.username)

class Destination(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField()
    description = models.TextField()
    price = models.IntegerField()
    def __str__(self):
        return self.description

class UserSelection(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    def get_userselection(self):
        return {
            'user': user,
            'destination': destination,
            'transaction_id': transaction_id,
        }

myapp/forms.py
from django import forms
from .models import User

from django.forms import Form
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm

from .models import *

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

    def clean(self):
        super(UserRegisterForm, self).clean()
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if len(username) < 8:
            self._errors['username'] = self.error_class(['Minimum 8 characters required'])
        if User.objects.filter(username=username).exists():
            self._errors['username'] = self.error_class(['Username already taken.'])
        if User.objects.filter(email=email).exists():
            self._errors['email'] = self.error_class(['Email address already taken.'])

        return self.cleaned_data

class UserCreateForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'role']

    def clean(self):
        super(UserCreateForm, self).clean()
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        role = self.cleaned_data.get('role')

        if len(username) < 8:
            self._errors['username'] = self.error_class(['Minimum 8 characters required'])
        if User.objects.filter(username=username).exists():
            self._errors['username'] = self.error_class(['Username already taken.'])
        if User.objects.filter(email=email).exists():
            self._errors['email'] = self.error_class(['Email address already taken.'])
        if role == None:
            self._errors['role'] = self.error_class(['Select a role for this user.'])

        return self.cleaned_data

class DestinationCreateForm(ModelForm):
    class Meta:
        model = Destination
        fields = ['name', 'description', 'image', 'price']

class PaymentForm(Form):
    nameOnCard = forms.CharField(max_length=50)

myapp/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.template import loader
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages

from urllib.parse import urlencode
import requests
import json

from django.conf import settings
from .models import *
from .forms import *
from .roles import *

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'myapp/index.html'
    context_object_name = 'destinations_list'
    def get_queryset(self):
        return Destination.objects.all()

class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = reverse_lazy('myapp:login')
    redirect_field_name = 'redirect_to'
    model = Destination
    template_name = 'myapp/detail.html'

class AdminPanelView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
    login_url = reverse_lazy('myapp:login')
    redirect_field_name = 'redirect_to'
    template_name = 'myapp/site_panel.html'
    def test_func(self):
        user = self.request.user
        return user.is_superuser or user.role == 2

class UsersView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    login_url = reverse_lazy('myapp:login')
    redirect_field_name = 'redirect_to'
    permission_required = ('myapp.view_user')
    raise_exception = True
    template_name = 'myapp/view_users.html'
    context_object_name = 'user_list'
    def get_queryset(self):
        return User.objects.order_by('pk')

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
@permission_required('myapp.add_user', raise_exception=True)
def create_user(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user.role == 2:
                user.groups.add(moderator_group)
            elif user.role == 1:
                user.groups.add(clientuser_group)
            messages.success(request, 'Account has been Created Successfully!!')
            return HttpResponseRedirect(reverse('myapp:view_users'))
    else:
        form = UserCreateForm()
    return render(request, 'myapp/create_user.html', {'form': form})

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
@permission_required('myapp.delete_user', raise_exception=True)
def delete_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    user.delete()
    messages.success(request, 'Account has been Deleted Successfully!!')
    return HttpResponseRedirect(reverse('myapp:view_users'))

class DestinationsView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    login_url = reverse_lazy('myapp:login')
    redirect_field_name = 'redirect_to'
    permission_required = ('myapp.view_destination')
    raise_exception = True
    template_name = 'myapp/view_destinations.html'
    context_object_name = 'destination_list'
    def get_queryset(self):
        return Destination.objects.order_by('pk')

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
@permission_required('myapp.add_destination', raise_exception=True)
def create_destination(request):
    if request.method == 'POST':
        form = DestinationCreateForm(request.POST, request.FILES)
        if form.is_valid():
            destination = form.save()
            messages.success(request, 'Destination has been Created Successfully!!')
            return HttpResponseRedirect(reverse('myapp:view_destinations'))
    else:
        form = DestinationCreateForm()
    return render(request, 'myapp/create_destination.html', {'form': form})

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
@permission_required('myapp.delete_destination', raise_exception=True)
def delete_destination(request, pk):
    destination = get_object_or_404(Destination, pk=pk)
    destination.delete()
    messages.success(request, 'Destination has been Deleted Successfully!!')
    return HttpResponseRedirect(reverse('myapp:view_destinations'))

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            #------reCAPTCHA Validation----------------#
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urlencode(values).encode()
            headers = {"Content-Type": "application/x-www-form-urlencoded"}
            response = requests.post(url, data=data, headers=headers)
            result = response.json()
            #-------End reCAPTCHA validation-------------#
            if result['success']:
                user = form.save()
                user.groups.add(clientuser_group)
                messages.success(request, 'Your Account has been Created Successfully!!')
                return redirect('myapp:login')
            else:
                messages.warning(request, 'Invalid reCAPTCHA. Please try again.')
    else:
        if request.user.is_authenticated:
            return redirect('myapp:index')
        else:
            form = UserRegisterForm()
    return render(request, 'myapp/register.html', {'form': form})

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('myapp:change_password')
        else:
            messages.warning(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'myapp/change_password.html', { 'form': form })

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def select(request, pk):
    destination = get_object_or_404(Destination, pk=pk)
    userselection = UserSelection.objects.filter(user=request.user, destination=destination)
    if len(userselection):
        messages.warning(request, "You had already selected this destination.")
        return HttpResponseRedirect(reverse('myapp:profile'))
    else:
        return HttpResponseRedirect(reverse('myapp:make_payment', args=[pk,]))

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def deselect(request, pk):
    userselection = get_object_or_404(UserSelection, pk=pk)
    userselection.delete()
    messages.success(request, 'Your selection was successfully recorded!')
    return HttpResponseRedirect(reverse('myapp:profile'))

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def profile(request):
    user = User.objects.get(pk=request.user.id)
    selections = UserSelection.objects.filter(user=user)
    return render(request, 'myapp/profile.html', {'selections': selections})

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def make_payment(request, pk):
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            stripeToken = request.POST['stripeToken']
            nameOnCard = request.POST['nameOnCard']
            customer = stripe.Customer.create(
                email = request.user.email,
                name = nameOnCard,
                description = 'Website Customer',
                source = stripeToken,
            )
            destination = get_object_or_404(Destination, pk=pk)
            price = destination.price * 100
            charge = stripe.Charge.create(
                customer = customer['id'],
                amount = price,
                currency = 'USD',
                description = 'Example charge',
            )
            userselection = UserSelection(
                user = request.user,
                destination = destination,
                transaction_id = charge['id']
            )
            userselection.save()
            messages.success(request, 'Your selection was successfully recorded!')
            return HttpResponseRedirect(reverse('myapp:payment_success', args=[pk,]))
        else:
            messages.warning(request, 'Please correct the error below.')
    else:
        form = PaymentForm()
    return  render(request, 'myapp/payment.html', {'form': form, 'pk': pk})

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def payment_success(request, pk):
    return render(request, 'myapp/payment_success.html')

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% if title %}
  		<title>Travel - {{ title }}</title>
  	{% else %}
  		<title>Travel</title>
  	{% endif %}
</head>
<body>
</br></br>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        {% if user.is_authenticated %}
          Hello, {{ user.username }}.
          <a href="{% url 'myapp:logout' %}"> Not you? </a>
        {% endif %}
      </div>
      <div class="col-md-3 text-right">
        {% if user.is_authenticated %}
          {% if user.is_superuser or user.role == 2 %}
            <span class="text-right">
              <a href="{% url 'myapp:admin_panel' %}">Admin Panel</a>
            </span>
          {% endif %}
        {% endif %}
      </div>
      {% if user.is_authenticated %}
        <div class="col-md-3">
          <a href="{% url 'myapp:profile' %}">Profile</a>
          &nbsp;
          <a href="{% url 'myapp:change_password' %}">Password</a>
          &nbsp;
          <a href="{% url 'myapp:logout' %}">Logout</a>
        </div>
      {% else %}
        <div class="col-md-3">
          <a href="{% url 'myapp:login' %}">Login</a>
          &nbsp;
          <a href="{% url 'myapp:register' %}">Register</a>
        </div>
      {% endif %}
    </div>
    <div class="row">
      <div class="col-md-8">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>
</html>
{% block footer_javascript_page %}
<script src="https://js.stripe.com/v3/" type="text/javascript"></script>
<script src="{% static '/myapp/js/payment_client.js' %}" type="text/javascript"></script>
{% endblock footer_javascript_page %}

myapp/templates/myapp/change_password.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Update Password{% endblock %}
{% block content %}
	<legend class="border-bottom mb-4">
		<a href="{% url 'myapp:index' %}">Travel</a> - Change Password
	</legend>
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Update</button>
			</div>
		</form>
	</div>
{% endblock content %}

myapp/templates/myapp/create_destination.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Destination{% endblock %}
{% block content %}
	<legend class="border-bottom mb-4">
		<a href="{% url 'myapp:index' %}">Travel</a> - Create Destination
	</legend>
	<div class="content-section">
		<form enctype="multipart/form-data" method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Submit</button>
			</div>
		</form>
	</div>
{% endblock content %}

myapp/templates/myapp/create_user.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create User{% endblock %}
{% block content %}
	<legend class="border-bottom mb-4">
		<a href="{% url 'myapp:index' %}">Travel</a> - Create User
	</legend>
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Submit</button>
			</div>
		</form>
	</div>
{% endblock content %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block title %}Detail{% endblock %}
{% block content %}

  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - Details Page
  </legend>

  <h5> {{destination.name}} - {{destination.price}}$ </h5>

  <div>
    <div class="mb-4">
      <img src="{{destination.image.url}}" alt="{{destination.name}}">
    </div>
    <div>
      <div> {{destination.description}} </div>
    </div>
  </div>

  <legend class="border-bottom mb-4"></legend>

  <a href="{% url 'myapp:select' destination.id %}">
    <button class="btn btn-outline-info"> Select </button>
  </a>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block title %}Index{% endblock %}
{% block content %}
  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - Index Page
  </legend>
  <div class="content-section">
  {% if destinations_list %}
    <!-- Destination -->
    {% for dest in destinations_list %}
      <div>
        <div class="mb-4">
          <a href="{% url 'myapp:detail' dest.pk %}">
            <img src="{{dest.image.url}}" alt="{{dest.name}}">
          </a>
        </div>
        <div>
          <div> {{dest.name}} - {{dest.price}}$ </div>
          <div> {{dest.description}} </div>
        </div>
      </div>
      <legend class="border-bottom mb-4"></legend>
    {% endfor %}
    <!-- Destination -->
  {% else %}
    <div class="alert alert-info">
			No destinations are available.
		</div>
  {% endif %}
  </div>
{% endblock %}

myapp/templates/myapp/logout.html
{% extends "myapp/base.html" %}

{% block title %}Logout{% endblock %}
{% block content %}
	<legend class="border-bottom mb-4">
		<a href="{% url 'myapp:index' %}">Travel</a> - User Logout
	</legend>
	<div class="content-section">
		<div class="alert alert-info">
			You have been successfully logged out.
		</div>
	</div>
{% endblock content %}

myapp/templates/myapp/password_reset.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Password Reset{% endblock %}
{% block content %}
	<legend class="border-bottom mb-4">
		<a href="{% url 'myapp:index' %}">Travel</a> - Reset Password
	</legend>
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Request Password Reset</button>
			</div>
		</form>
	</div>
{% endblock content %}

myapp/templates/myapp/password_reset_complete.html
{% extends "myapp/base.html" %}

{% block title %}Password Reset Complete{% endblock %}
{% block content %}
	<legend class="border-bottom mb-4">
		<a href="{% url 'myapp:index' %}">Travel</a> - Reset Password Complete
	</legend>
	<div class="content-section">
		<div class="alert alert-info">
			Your password has been set!
		</div>
	</div>
{% endblock content %}

myapp/templates/myapp/payment.html
{% extends 'myapp/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Make Payment{% endblock %}
{% block content %}
  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - Make Payment
  </legend>

	<form action="{% url 'myapp:make_payment' pk %}" method="POST" id="payment-form">
		{% csrf_token %}
    <div>
      {{ form|crispy }}
    </div>

    <div>
      <label for="card-element">
        Credit or debit card
      </label>
      <div id="card-element">
        <!-- A Stripe Element will be inserted here. -->
      </div>
      <!-- Used to display form errors. -->
      <div id="card-errors" role="alert"></div>
    </div>

    <legend class="border-bottom mb-4"></legend>
		<button class="btn btn-outline-info" type="submit">Submit</button>
	</form>
{% endblock content %}

myapp/templates/myapp/profile.html
{% extends 'myapp/base.html' %}

{% block title %}Profile{% endblock %}
{% block content %}

  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - Profile Page
  </legend>

  {% if selections %}
  <p>
    {% for selection in selections %}
      <p style="margin:0;padding:0;">
        <a href="{% url 'myapp:deselect' selection.id %}">
          <button class="btn"><i class="fa fa-trash"></i></button>
        </a>
        <a href="{% url 'myapp:detail' selection.destination.id %}">
          {{ selection.destination.name }}
        </a>
      </p>
    {% endfor %}
  </p>
  {% else %}
    <p>No destinations selected.</p>
  {% endif %}

{% endblock %}

myapp/templates/myapp/register.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}
{% block content %}
	<legend class="border-bottom mb-4">
		<a href="{% url 'myapp:index' %}">Travel</a> - User Registration
	</legend>
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ form|crispy }}
			</fieldset>
			<div class="form-group"></div>
     		<script src="https://www.google.com/recaptcha/api.js" ></script>
    		<div class="g-recaptcha" data-sitekey="6LfLO-IUAAAAALPnnqdQRNCUJKFR2K2vwvrGPxYl"></div>
    		<br/>
    		<button class="btn btn-outline-info" type="submit">Submit</button>
			</div>
		</form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{% url 'myapp:login' %}">Sign In</a>
      </small>
    </div>
{% endblock content %}

myapp/templates/myapp/view_destinations.html
{% extends 'myapp/base.html' %}

{% block title %}Destination Management{% endblock %}
{% block content %}

  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - Destination List
  </legend>

  <a href="{% url 'myapp:create_destination' %}">Click Here</a> - To Add Another Destination

  {% if destination_list %}
      <p>
        {% for destination in destination_list %}
            <p style="margin:0;padding:0;">
              <a href="{% url 'myapp:delete_destination' destination.pk %}">
                <button class="btn"><i class="fa fa-trash"></i></button>
              </a>
              <a href="{% url 'myapp:detail' destination.pk %}">
                {{ destination.name }}
              </a>
            </p>
        {% endfor %}
      </p>
  {% else %}
      <p>No destinations are available.</p>
  {% endif %}

{% endblock %}

myapp/templates/myapp/view_users.html
{% extends 'myapp/base.html' %}

{% block title %}User Management{% endblock %}
{% block content %}

  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - User List
  </legend>

  <a href="{% url 'myapp:create_user' %}">Click Here</a> - To Add Another User

  {% if user_list %}
      <p>
        {% for user in user_list %}
            <p style="margin:0;padding:0;">
              <a href="{% url 'myapp:delete_user' user.pk %}">
                <button class="btn"><i class="fa fa-trash"></i></button>
              </a>
              &nbsp;&nbsp; {{ user.username }}
              {% if user.last_name %}
                - {{ user.last_name }},
              {% endif %}
              {% if user.last_name %}
                {{ user.first_name }}
              {% endif %}
            </p>
        {% endfor %}
      </p>
  {% else %}
      <p>No users are available.</p>
  {% endif %}

{% endblock %}